//
// GenerateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class GenerateAPI {
    /**
     Generate a barcode using a GET request with parameters in the route and query string.

     - parameter barcodeType: (path) Type of barcode to generate.
     - parameter data: (query) String that represents the data to encode.
     - parameter dataType: (query) Type of data to encode. Default value: StringData. (optional)
     - parameter barcodeImageParams: (BarcodeImageParams) Grouped barcodeImageParams parameters.
     - parameter qrParams: (QrParams) Grouped qrParams parameters.
     - parameter code128Params: (Code128Params) Grouped code128Params parameters.
     - parameter pdf417Params: (Pdf417Params) Grouped pdf417Params parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func generate(barcodeType: EncodeBarcodeType, data: String, dataType: EncodeDataType? = nil, barcodeImageParams: BarcodeImageParams? = nil, qrParams: QrParams? = nil, code128Params: Code128Params? = nil, pdf417Params: Pdf417Params? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: Data?, _ error: Error?) -> Void) -> RequestTask {
        generateWithRequestBuilder(barcodeType: barcodeType, data: data, dataType: dataType, barcodeImageParams: barcodeImageParams, qrParams: qrParams, code128Params: code128Params, pdf417Params: pdf417Params, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Generate a barcode using a GET request with parameters in the route and query string.

     - parameter barcodeType: (path) Type of barcode to generate.
     - parameter data: (query) String that represents the data to encode.
     - parameter dataType: (query) Type of data to encode. Default value: StringData. (optional)
     - parameter barcodeImageParams: (BarcodeImageParams) Grouped barcodeImageParams parameters.
     - parameter qrParams: (QrParams) Grouped qrParams parameters.
     - parameter code128Params: (Code128Params) Grouped code128Params parameters.
     - parameter pdf417Params: (Pdf417Params) Grouped pdf417Params parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func generate(barcodeType: EncodeBarcodeType, data: String, dataType: EncodeDataType? = nil, barcodeImageParams: BarcodeImageParams? = nil, qrParams: QrParams? = nil, code128Params: Code128Params? = nil, pdf417Params: Pdf417Params? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        try await generateWithRequestBuilder(barcodeType: barcodeType, data: data, dataType: dataType, barcodeImageParams: barcodeImageParams, qrParams: qrParams, code128Params: code128Params, pdf417Params: pdf417Params, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Generate a barcode using a GET request with parameters in the route and query string.
     - GET /barcode/generate/{barcodeType}
     - OAuth:
       - type: oauth2
       - name: JWT

     - parameter barcodeType: (path) Type of barcode to generate.
     - parameter data: (query) String that represents the data to encode.
     - parameter dataType: (query) Type of data to encode. Default value: StringData. (optional)
     - parameter barcodeImageParams: (BarcodeImageParams) Grouped barcodeImageParams parameters.
     - parameter qrParams: (QrParams) Grouped qrParams parameters.
     - parameter code128Params: (Code128Params) Grouped code128Params parameters.
     - parameter pdf417Params: (Pdf417Params) Grouped pdf417Params parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data>
     */
    open class func generateWithRequestBuilder(barcodeType: EncodeBarcodeType, data: String, dataType: EncodeDataType? = nil, barcodeImageParams: BarcodeImageParams? = nil, qrParams: QrParams? = nil, code128Params: Code128Params? = nil, pdf417Params: Pdf417Params? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<Data> {
        var localVariablePath = "/barcode/generate/{barcodeType}"
        let barcodeTypePreEscape = "\(APIHelper.mapValueToPathItem(barcodeType))"
        let barcodeTypePostEscape = barcodeTypePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{barcodeType}", with: barcodeTypePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "dataType": (wrappedValue: dataType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "data": (wrappedValue: data.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "imageFormat": (wrappedValue: barcodeImageParams?.imageFormat?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "textLocation": (wrappedValue: barcodeImageParams?.textLocation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "foregroundColor": (wrappedValue: barcodeImageParams?.foregroundColor?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "backgroundColor": (wrappedValue: barcodeImageParams?.backgroundColor?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "units": (wrappedValue: barcodeImageParams?.units?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "resolution": (wrappedValue: barcodeImageParams?.resolution?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "imageHeight": (wrappedValue: barcodeImageParams?.imageHeight?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "imageWidth": (wrappedValue: barcodeImageParams?.imageWidth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "rotationAngle": (wrappedValue: barcodeImageParams?.rotationAngle?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "qrEncodeMode": (wrappedValue: qrParams?.qrEncodeMode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "qrErrorLevel": (wrappedValue: qrParams?.qrErrorLevel?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "qrVersion": (wrappedValue: qrParams?.qrVersion?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "qrECIEncoding": (wrappedValue: qrParams?.qrECIEncoding?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "qrAspectRatio": (wrappedValue: qrParams?.qrAspectRatio?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "microQRVersion": (wrappedValue: qrParams?.microQRVersion?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "rectMicroQrVersion": (wrappedValue: qrParams?.rectMicroQrVersion?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "code128EncodeMode": (wrappedValue: code128Params?.code128EncodeMode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417EncodeMode": (wrappedValue: pdf417Params?.pdf417EncodeMode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417ErrorLevel": (wrappedValue: pdf417Params?.pdf417ErrorLevel?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417Truncate": (wrappedValue: pdf417Params?.pdf417Truncate?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417Columns": (wrappedValue: pdf417Params?.pdf417Columns?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417Rows": (wrappedValue: pdf417Params?.pdf417Rows?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417AspectRatio": (wrappedValue: pdf417Params?.pdf417AspectRatio?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417ECIEncoding": (wrappedValue: pdf417Params?.pdf417ECIEncoding?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417IsReaderInitialization": (wrappedValue: pdf417Params?.pdf417IsReaderInitialization?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417MacroCharacters": (wrappedValue: pdf417Params?.pdf417MacroCharacters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417IsLinked": (wrappedValue: pdf417Params?.pdf417IsLinked?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pdf417IsCode128Emulation": (wrappedValue: pdf417Params?.pdf417IsCode128Emulation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [:]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Generate a barcode using a POST request with parameters in the request body in JSON or XML format.

     - parameter generateParams: (body) Generation parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func generateBody(generateParams: GenerateParams, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: Data?, _ error: Error?) -> Void) -> RequestTask {
        generateBodyWithRequestBuilder(generateParams: generateParams, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Generate a barcode using a POST request with parameters in the request body in JSON or XML format.

     - parameter generateParams: (body) Generation parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func generateBody(generateParams: GenerateParams, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        try await generateBodyWithRequestBuilder(generateParams: generateParams, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Generate a barcode using a POST request with parameters in the request body in JSON or XML format.
     - POST /barcode/generate-body
     - OAuth:
       - type: oauth2
       - name: JWT

     - parameter generateParams: (body) Generation parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data>
     */
    open class func generateBodyWithRequestBuilder(generateParams: GenerateParams, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<Data> {
        let localVariablePath = "/barcode/generate-body"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: generateParams, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Generate a barcode using a POST request with parameters in a multipart form.

     - parameter barcodeType: (form) See https://reference.aspose.com/barcode/net/aspose.barcode.generation/encodetypes/
     - parameter data: (form) String that represents the data to encode.
     - parameter dataType: (form) Type of data to encode. Default value: StringData. (optional)
     - parameter barcodeImageParams: (BarcodeImageParams) Grouped barcodeImageParams parameters.
     - parameter qrParams: (QrParams) Grouped qrParams parameters.
     - parameter code128Params: (Code128Params) Grouped code128Params parameters.
     - parameter pdf417Params: (Pdf417Params) Grouped pdf417Params parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func generateMultipart(barcodeType: EncodeBarcodeType, data: String, dataType: EncodeDataType? = nil, barcodeImageParams: BarcodeImageParams? = nil, qrParams: QrParams? = nil, code128Params: Code128Params? = nil, pdf417Params: Pdf417Params? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: Data?, _ error: Error?) -> Void) -> RequestTask {
        generateMultipartWithRequestBuilder(barcodeType: barcodeType, data: data, dataType: dataType, barcodeImageParams: barcodeImageParams, qrParams: qrParams, code128Params: code128Params, pdf417Params: pdf417Params, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Generate a barcode using a POST request with parameters in a multipart form.

     - parameter barcodeType: (form) See https://reference.aspose.com/barcode/net/aspose.barcode.generation/encodetypes/
     - parameter data: (form) String that represents the data to encode.
     - parameter dataType: (form) Type of data to encode. Default value: StringData. (optional)
     - parameter barcodeImageParams: (BarcodeImageParams) Grouped barcodeImageParams parameters.
     - parameter qrParams: (QrParams) Grouped qrParams parameters.
     - parameter code128Params: (Code128Params) Grouped code128Params parameters.
     - parameter pdf417Params: (Pdf417Params) Grouped pdf417Params parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func generateMultipart(barcodeType: EncodeBarcodeType, data: String, dataType: EncodeDataType? = nil, barcodeImageParams: BarcodeImageParams? = nil, qrParams: QrParams? = nil, code128Params: Code128Params? = nil, pdf417Params: Pdf417Params? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        try await generateMultipartWithRequestBuilder(barcodeType: barcodeType, data: data, dataType: dataType, barcodeImageParams: barcodeImageParams, qrParams: qrParams, code128Params: code128Params, pdf417Params: pdf417Params, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Generate a barcode using a POST request with parameters in a multipart form.
     - POST /barcode/generate-multipart
     - OAuth:
       - type: oauth2
       - name: JWT

     - parameter barcodeType: (form) See https://reference.aspose.com/barcode/net/aspose.barcode.generation/encodetypes/
     - parameter data: (form) String that represents the data to encode.
     - parameter dataType: (form) Type of data to encode. Default value: StringData. (optional)
     - parameter barcodeImageParams: (BarcodeImageParams) Grouped barcodeImageParams parameters.
     - parameter qrParams: (QrParams) Grouped qrParams parameters.
     - parameter code128Params: (Code128Params) Grouped code128Params parameters.
     - parameter pdf417Params: (Pdf417Params) Grouped pdf417Params parameters.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data>
     */
    open class func generateMultipartWithRequestBuilder(barcodeType: EncodeBarcodeType, data: String, dataType: EncodeDataType? = nil, barcodeImageParams: BarcodeImageParams? = nil, qrParams: QrParams? = nil, code128Params: Code128Params? = nil, pdf417Params: Pdf417Params? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<Data> {
        let localVariablePath = "/barcode/generate-multipart"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "barcodeType": barcodeType.asParameter(codableHelper: apiConfiguration.codableHelper),
            "dataType": dataType?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "data": data.asParameter(codableHelper: apiConfiguration.codableHelper),
            "imageFormat": barcodeImageParams?.imageFormat?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "textLocation": barcodeImageParams?.textLocation?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "foregroundColor": barcodeImageParams?.foregroundColor?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "backgroundColor": barcodeImageParams?.backgroundColor?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "units": barcodeImageParams?.units?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "resolution": barcodeImageParams?.resolution?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "imageHeight": barcodeImageParams?.imageHeight?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "imageWidth": barcodeImageParams?.imageWidth?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "rotationAngle": barcodeImageParams?.rotationAngle?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "qrEncodeMode": qrParams?.qrEncodeMode?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "qrErrorLevel": qrParams?.qrErrorLevel?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "qrVersion": qrParams?.qrVersion?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "qrECIEncoding": qrParams?.qrECIEncoding?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "qrAspectRatio": qrParams?.qrAspectRatio?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "microQRVersion": qrParams?.microQRVersion?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "rectMicroQrVersion": qrParams?.rectMicroQrVersion?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "code128EncodeMode": code128Params?.code128EncodeMode?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417EncodeMode": pdf417Params?.pdf417EncodeMode?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417ErrorLevel": pdf417Params?.pdf417ErrorLevel?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417Truncate": pdf417Params?.pdf417Truncate?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417Columns": pdf417Params?.pdf417Columns?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417Rows": pdf417Params?.pdf417Rows?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417AspectRatio": pdf417Params?.pdf417AspectRatio?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417ECIEncoding": pdf417Params?.pdf417ECIEncoding?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417IsReaderInitialization": pdf417Params?.pdf417IsReaderInitialization?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417MacroCharacters": pdf417Params?.pdf417MacroCharacters?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417IsLinked": pdf417Params?.pdf417IsLinked?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "pdf417IsCode128Emulation": pdf417Params?.pdf417IsCode128Emulation?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
