//
// RecognizeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RecognizeAPI {

    /**
     Recognize barcode from file on server in the Internet using GET requests with parameter in query string. For recognizing files from your hard drive use `recognize-body` or `recognize-multipart` endpoints instead.
     
     - parameter barcodeType: (query) Type of barcode to recognize 
     - parameter fileUrl: (query) Url to barcode image 
     - parameter recognitionMode: (query) Recognition mode (optional)
     - parameter recognitionImageKind: (query) Image kind for recognition (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recognize(barcodeType: DecodeBarcodeType, fileUrl: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiResponseQueue: DispatchQueue = AsposeBarcodeCloudAPI.apiResponseQueue, completion: @escaping ((_ data: BarcodeResponseList?, _ error: Error?) -> Void)) -> RequestTask {
        return recognizeWithRequestBuilder(barcodeType: barcodeType, fileUrl: fileUrl, recognitionMode: recognitionMode, recognitionImageKind: recognitionImageKind).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Recognize barcode from file on server in the Internet using GET requests with parameter in query string. For recognizing files from your hard drive use `recognize-body` or `recognize-multipart` endpoints instead.
     - GET /barcode/recognize
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter barcodeType: (query) Type of barcode to recognize 
     - parameter fileUrl: (query) Url to barcode image 
     - parameter recognitionMode: (query) Recognition mode (optional)
     - parameter recognitionImageKind: (query) Image kind for recognition (optional)
     - returns: RequestBuilder<BarcodeResponseList> 
     */
    open class func recognizeWithRequestBuilder(barcodeType: DecodeBarcodeType, fileUrl: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/recognize"
        let localVariableURLString = AsposeBarcodeCloudAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "barcodeType": (wrappedValue: barcodeType.encodeToJSON(), isExplode: true),
            "fileUrl": (wrappedValue: fileUrl.encodeToJSON(), isExplode: true),
            "recognitionMode": (wrappedValue: recognitionMode?.encodeToJSON(), isExplode: true),
            "recognitionImageKind": (wrappedValue: recognitionImageKind?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = AsposeBarcodeCloudAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Recognize barcode from file in request body using POST requests with parameters in body in json or xml format.
     
     - parameter recognizeBase64Request: (body) Barcode recognition request 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recognizeBase64(recognizeBase64Request: RecognizeBase64Request, apiResponseQueue: DispatchQueue = AsposeBarcodeCloudAPI.apiResponseQueue, completion: @escaping ((_ data: BarcodeResponseList?, _ error: Error?) -> Void)) -> RequestTask {
        return recognizeBase64WithRequestBuilder(recognizeBase64Request: recognizeBase64Request).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Recognize barcode from file in request body using POST requests with parameters in body in json or xml format.
     - POST /barcode/recognize-body
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter recognizeBase64Request: (body) Barcode recognition request 
     - returns: RequestBuilder<BarcodeResponseList> 
     */
    open class func recognizeBase64WithRequestBuilder(recognizeBase64Request: RecognizeBase64Request) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/recognize-body"
        let localVariableURLString = AsposeBarcodeCloudAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: recognizeBase64Request)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = AsposeBarcodeCloudAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Recognize barcode from file in request body using POST requests with parameters in multipart form.
     
     - parameter barcodeType: (form)  
     - parameter file: (form) Barcode image file 
     - parameter recognitionMode: (form)  (optional)
     - parameter recognitionImageKind: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recognizeMultipart(barcodeType: DecodeBarcodeType, file: Data, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiResponseQueue: DispatchQueue = AsposeBarcodeCloudAPI.apiResponseQueue, completion: @escaping ((_ data: BarcodeResponseList?, _ error: Error?) -> Void)) -> RequestTask {
        return recognizeMultipartWithRequestBuilder(barcodeType: barcodeType, file: file, recognitionMode: recognitionMode, recognitionImageKind: recognitionImageKind).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Recognize barcode from file in request body using POST requests with parameters in multipart form.
     - POST /barcode/recognize-multipart
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter barcodeType: (form)  
     - parameter file: (form) Barcode image file 
     - parameter recognitionMode: (form)  (optional)
     - parameter recognitionImageKind: (form)  (optional)
     - returns: RequestBuilder<BarcodeResponseList> 
     */
    open class func recognizeMultipartWithRequestBuilder(barcodeType: DecodeBarcodeType, file: Data, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/recognize-multipart"
        let localVariableURLString = AsposeBarcodeCloudAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "barcodeType": barcodeType.encodeToJSON(),
            "file": file.encodeToJSON(),
            "recognitionMode": recognitionMode?.encodeToJSON(),
            "recognitionImageKind": recognitionImageKind?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = AsposeBarcodeCloudAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
