//
// RecognizeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RecognizeAPI {
    /**
     Recognize a barcode from a file on an Internet server using a GET request with a query string parameter. For recognizing files from your hard drive, use `recognize-body` or `recognize-multipart` endpoints instead.

     - parameter barcodeType: (query) Type of barcode to recognize.
     - parameter fileUrl: (query) URL to the barcode image.
     - parameter recognitionMode: (query) Recognition mode. (optional)
     - parameter recognitionImageKind: (query) Image kind for recognition. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recognize(barcodeType: DecodeBarcodeType, fileUrl: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: BarcodeResponseList?, _ error: Error?) -> Void) -> RequestTask {
        recognizeWithRequestBuilder(barcodeType: barcodeType, fileUrl: fileUrl, recognitionMode: recognitionMode, recognitionImageKind: recognitionImageKind, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Recognize a barcode from a file on an Internet server using a GET request with a query string parameter. For recognizing files from your hard drive, use `recognize-body` or `recognize-multipart` endpoints instead.

     - parameter barcodeType: (query) Type of barcode to recognize.
     - parameter fileUrl: (query) URL to the barcode image.
     - parameter recognitionMode: (query) Recognition mode. (optional)
     - parameter recognitionImageKind: (query) Image kind for recognition. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BarcodeResponseList
     */
    open class func recognize(barcodeType: DecodeBarcodeType, fileUrl: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> BarcodeResponseList {
        try await recognizeWithRequestBuilder(barcodeType: barcodeType, fileUrl: fileUrl, recognitionMode: recognitionMode, recognitionImageKind: recognitionImageKind, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Recognize a barcode from a file on an Internet server using a GET request with a query string parameter. For recognizing files from your hard drive, use `recognize-body` or `recognize-multipart` endpoints instead.
     - GET /barcode/recognize
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter barcodeType: (query) Type of barcode to recognize.
     - parameter fileUrl: (query) URL to the barcode image.
     - parameter recognitionMode: (query) Recognition mode. (optional)
     - parameter recognitionImageKind: (query) Image kind for recognition. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BarcodeResponseList>
     */
    open class func recognizeWithRequestBuilder(barcodeType: DecodeBarcodeType, fileUrl: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/recognize"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "barcodeType": (wrappedValue: barcodeType.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "fileUrl": (wrappedValue: fileUrl.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "recognitionMode": (wrappedValue: recognitionMode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "recognitionImageKind": (wrappedValue: recognitionImageKind?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [:]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Recognize a barcode from a file in the request body using a POST request with JSON or XML body parameters.

     - parameter recognizeBase64Request: (body) Barcode recognition request.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recognizeBase64(recognizeBase64Request: RecognizeBase64Request, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: BarcodeResponseList?, _ error: Error?) -> Void) -> RequestTask {
        recognizeBase64WithRequestBuilder(recognizeBase64Request: recognizeBase64Request, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Recognize a barcode from a file in the request body using a POST request with JSON or XML body parameters.

     - parameter recognizeBase64Request: (body) Barcode recognition request.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BarcodeResponseList
     */
    open class func recognizeBase64(recognizeBase64Request: RecognizeBase64Request, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> BarcodeResponseList {
        try await recognizeBase64WithRequestBuilder(recognizeBase64Request: recognizeBase64Request, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Recognize a barcode from a file in the request body using a POST request with JSON or XML body parameters.
     - POST /barcode/recognize-body
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter recognizeBase64Request: (body) Barcode recognition request.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BarcodeResponseList>
     */
    open class func recognizeBase64WithRequestBuilder(recognizeBase64Request: RecognizeBase64Request, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/recognize-body"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: recognizeBase64Request, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Recognize a barcode from a file in the request body using a POST request with multipart form parameters.

     - parameter barcodeType: (form) See https://reference.aspose.com/barcode/net/aspose.barcode.barcoderecognition/decodetype/
     - parameter file: (form) Barcode image file.
     - parameter recognitionMode: (form) Recognition mode. (optional)
     - parameter recognitionImageKind: (form) Image kind for recognition. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recognizeMultipart(barcodeType: DecodeBarcodeType, file: Data, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: BarcodeResponseList?, _ error: Error?) -> Void) -> RequestTask {
        recognizeMultipartWithRequestBuilder(barcodeType: barcodeType, file: file, recognitionMode: recognitionMode, recognitionImageKind: recognitionImageKind, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Recognize a barcode from a file in the request body using a POST request with multipart form parameters.

     - parameter barcodeType: (form) See https://reference.aspose.com/barcode/net/aspose.barcode.barcoderecognition/decodetype/
     - parameter file: (form) Barcode image file.
     - parameter recognitionMode: (form) Recognition mode. (optional)
     - parameter recognitionImageKind: (form) Image kind for recognition. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BarcodeResponseList
     */
    open class func recognizeMultipart(barcodeType: DecodeBarcodeType, file: Data, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> BarcodeResponseList {
        try await recognizeMultipartWithRequestBuilder(barcodeType: barcodeType, file: file, recognitionMode: recognitionMode, recognitionImageKind: recognitionImageKind, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Recognize a barcode from a file in the request body using a POST request with multipart form parameters.
     - POST /barcode/recognize-multipart
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter barcodeType: (form) See https://reference.aspose.com/barcode/net/aspose.barcode.barcoderecognition/decodetype/
     - parameter file: (form) Barcode image file.
     - parameter recognitionMode: (form) Recognition mode. (optional)
     - parameter recognitionImageKind: (form) Image kind for recognition. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BarcodeResponseList>
     */
    open class func recognizeMultipartWithRequestBuilder(barcodeType: DecodeBarcodeType, file: Data, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/recognize-multipart"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "barcodeType": barcodeType.asParameter(codableHelper: apiConfiguration.codableHelper),
            "file": file,
            "recognitionMode": recognitionMode?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "recognitionImageKind": recognitionImageKind?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
