//
// ScanAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ScanAPI {
    /**
     Scan a barcode from a file on an Internet server using a GET request with a query string parameter. For scanning files from your hard drive, use `scan-body` or `scan-multipart` endpoints instead.

     - parameter fileUrl: (query) URL to the barcode image.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scan(fileUrl: String, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: BarcodeResponseList?, _ error: Error?) -> Void) -> RequestTask {
        scanWithRequestBuilder(fileUrl: fileUrl, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Scan a barcode from a file on an Internet server using a GET request with a query string parameter. For scanning files from your hard drive, use `scan-body` or `scan-multipart` endpoints instead.

     - parameter fileUrl: (query) URL to the barcode image.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BarcodeResponseList
     */
    open class func scan(fileUrl: String, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> BarcodeResponseList {
        try await scanWithRequestBuilder(fileUrl: fileUrl, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Scan a barcode from a file on an Internet server using a GET request with a query string parameter. For scanning files from your hard drive, use `scan-body` or `scan-multipart` endpoints instead.
     - GET /barcode/scan
     - OAuth:
       - type: oauth2
       - name: JWT

     - parameter fileUrl: (query) URL to the barcode image.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BarcodeResponseList>
     */
    open class func scanWithRequestBuilder(fileUrl: String, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/scan"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "fileUrl": (wrappedValue: fileUrl.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [:]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Scan a barcode from a file in the request body using a POST request with a JSON or XML body parameter.

     - parameter scanBase64Request: (body) Barcode scan request.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scanBase64(scanBase64Request: ScanBase64Request, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: BarcodeResponseList?, _ error: Error?) -> Void) -> RequestTask {
        scanBase64WithRequestBuilder(scanBase64Request: scanBase64Request, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Scan a barcode from a file in the request body using a POST request with a JSON or XML body parameter.

     - parameter scanBase64Request: (body) Barcode scan request.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BarcodeResponseList
     */
    open class func scanBase64(scanBase64Request: ScanBase64Request, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> BarcodeResponseList {
        try await scanBase64WithRequestBuilder(scanBase64Request: scanBase64Request, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Scan a barcode from a file in the request body using a POST request with a JSON or XML body parameter.
     - POST /barcode/scan-body
     - OAuth:
       - type: oauth2
       - name: JWT

     - parameter scanBase64Request: (body) Barcode scan request.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BarcodeResponseList>
     */
    open class func scanBase64WithRequestBuilder(scanBase64Request: ScanBase64Request, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/scan-body"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: scanBase64Request, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Scan a barcode from a file in the request body using a POST request with a multipart form parameter.

     - parameter file: (form) Barcode image file.
     - parameter apiConfiguration: The configuration for the http request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scanMultipart(file: Data, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared, completion: @Sendable @escaping (_ data: BarcodeResponseList?, _ error: Error?) -> Void) -> RequestTask {
        scanMultipartWithRequestBuilder(file: file, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Scan a barcode from a file in the request body using a POST request with a multipart form parameter.

     - parameter file: (form) Barcode image file.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BarcodeResponseList
     */
    open class func scanMultipart(file: Data, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) async throws(ErrorResponse) -> BarcodeResponseList {
        try await scanMultipartWithRequestBuilder(file: file, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Scan a barcode from a file in the request body using a POST request with a multipart form parameter.
     - POST /barcode/scan-multipart
     - OAuth:
       - type: oauth2
       - name: JWT

     - parameter file: (form) Barcode image file.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BarcodeResponseList>
     */
    open class func scanMultipartWithRequestBuilder(file: Data, apiConfiguration: AsposeBarcodeCloudAPIConfiguration = AsposeBarcodeCloudAPIConfiguration.shared) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/scan-multipart"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "file": file,
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
