//
// ScanAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ScanAPI {

    /**
     Scan barcode from file on server in the Internet using GET requests with parameter in query string. For scaning files from your hard drive use `scan-body` or `scan-multipart` endpoints instead.
     
     - parameter fileUrl: (query) Url to barcode image 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scan(fileUrl: String, apiResponseQueue: DispatchQueue = AsposeBarcodeCloudAPI.apiResponseQueue, completion: @escaping ((_ data: BarcodeResponseList?, _ error: Error?) -> Void)) -> RequestTask {
        return scanWithRequestBuilder(fileUrl: fileUrl).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Scan barcode from file on server in the Internet using GET requests with parameter in query string. For scaning files from your hard drive use `scan-body` or `scan-multipart` endpoints instead.
     - GET /barcode/scan
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter fileUrl: (query) Url to barcode image 
     - returns: RequestBuilder<BarcodeResponseList> 
     */
    open class func scanWithRequestBuilder(fileUrl: String) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/scan"
        let localVariableURLString = AsposeBarcodeCloudAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "fileUrl": (wrappedValue: fileUrl.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = AsposeBarcodeCloudAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Scan barcode from file in request body using POST requests with parameter in body in json or xml format.
     
     - parameter scanBase64Request: (body) Barcode scan request 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scanBase64(scanBase64Request: ScanBase64Request, apiResponseQueue: DispatchQueue = AsposeBarcodeCloudAPI.apiResponseQueue, completion: @escaping ((_ data: BarcodeResponseList?, _ error: Error?) -> Void)) -> RequestTask {
        return scanBase64WithRequestBuilder(scanBase64Request: scanBase64Request).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Scan barcode from file in request body using POST requests with parameter in body in json or xml format.
     - POST /barcode/scan-body
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter scanBase64Request: (body) Barcode scan request 
     - returns: RequestBuilder<BarcodeResponseList> 
     */
    open class func scanBase64WithRequestBuilder(scanBase64Request: ScanBase64Request) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/scan-body"
        let localVariableURLString = AsposeBarcodeCloudAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: scanBase64Request)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = AsposeBarcodeCloudAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Scan barcode from file in request body using POST requests with parameter in multipart form.
     
     - parameter file: (form) Barcode image file 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func scanMultipart(file: Data, apiResponseQueue: DispatchQueue = AsposeBarcodeCloudAPI.apiResponseQueue, completion: @escaping ((_ data: BarcodeResponseList?, _ error: Error?) -> Void)) -> RequestTask {
        return scanMultipartWithRequestBuilder(file: file).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Scan barcode from file in request body using POST requests with parameter in multipart form.
     - POST /barcode/scan-multipart
     - OAuth:
       - type: oauth2
       - name: JWT
     - parameter file: (form) Barcode image file 
     - returns: RequestBuilder<BarcodeResponseList> 
     */
    open class func scanMultipartWithRequestBuilder(file: Data) -> RequestBuilder<BarcodeResponseList> {
        let localVariablePath = "/barcode/scan-multipart"
        let localVariableURLString = AsposeBarcodeCloudAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BarcodeResponseList>.Type = AsposeBarcodeCloudAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
