//
// ApiErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ApiError Response */
public final class ApiErrorResponse: Codable, JSONEncodable, Hashable {

    /** Gets or sets request Id. */
    public var requestId: String?
    public var error: ApiError

    public init(requestId: String?, error: ApiError) {
        self.requestId = requestId
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestId
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestId, forKey: .requestId)
        try container.encode(error, forKey: .error)
    }

    public static func == (lhs: ApiErrorResponse, rhs: ApiErrorResponse) -> Bool {
        lhs.requestId == rhs.requestId &&
        lhs.error == rhs.error
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(requestId.hashValue)
        hasher.combine(error.hashValue)
        
    }
}

