//
// ApiError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Api Error. */
public final class ApiError: Codable, JSONEncodable, Hashable {

    /** Gets or sets api error code. */
    public var code: String?
    /** Gets or sets error message. */
    public var message: String?
    /** Gets or sets error description. */
    public var description: String?
    /** Gets or sets server datetime. */
    public var dateTime: Date?
    public var innerError: ApiError?

    public init(code: String?, message: String?, description: String? = nil, dateTime: Date? = nil, innerError: ApiError? = nil) {
        self.code = code
        self.message = message
        self.description = description
        self.dateTime = dateTime
        self.innerError = innerError
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case description
        case dateTime
        case innerError
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(dateTime, forKey: .dateTime)
        try container.encodeIfPresent(innerError, forKey: .innerError)
    }

    public static func == (lhs: ApiError, rhs: ApiError) -> Bool {
        lhs.code == rhs.code &&
        lhs.message == rhs.message &&
        lhs.description == rhs.description &&
        lhs.dateTime == rhs.dateTime &&
        lhs.innerError == rhs.innerError
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(code.hashValue)
        hasher.combine(message.hashValue)
        hasher.combine(description?.hashValue)
        hasher.combine(dateTime?.hashValue)
        hasher.combine(innerError?.hashValue)
        
    }
}

