//
// BarcodeImageFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies the file format of the image. */
public enum BarcodeImageFormat: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case png = "Png"
    case jpeg = "Jpeg"
    case svg = "Svg"
    case tiff = "Tiff"
    case gif = "Gif"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
