//
// BarcodeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents information about barcode. */
public final class BarcodeResponse: @unchecked Sendable, Codable, Hashable {
    /** Barcode data. */
    public var barcodeValue: String?
    /** Type of the barcode. */
    public var type: String?
    /** Region with barcode. */
    public var region: [RegionPoint]?
    /** Checksum of barcode. */
    public var checksum: String?

    public init(barcodeValue: String? = nil, type: String? = nil, region: [RegionPoint]? = nil, checksum: String? = nil) {
        self.barcodeValue = barcodeValue
        self.type = type
        self.region = region
        self.checksum = checksum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case barcodeValue
        case type
        case region
        case checksum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(barcodeValue, forKey: .barcodeValue)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(checksum, forKey: .checksum)
    }

    public static func == (lhs: BarcodeResponse, rhs: BarcodeResponse) -> Bool {
        lhs.barcodeValue == rhs.barcodeValue &&
            lhs.type == rhs.type &&
            lhs.region == rhs.region &&
            lhs.checksum == rhs.checksum
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(barcodeValue?.hashValue)
        hasher.combine(type?.hashValue)
        hasher.combine(region?.hashValue)
        hasher.combine(checksum?.hashValue)
    }
}
