//
// BarcodeResponseList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represents information about barcode list. */
public final class BarcodeResponseList: Codable, JSONEncodable, Hashable {

    /** List of barcodes which are present in image. */
    public var barcodes: [BarcodeResponse]?

    public init(barcodes: [BarcodeResponse]?) {
        self.barcodes = barcodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case barcodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(barcodes, forKey: .barcodes)
    }

    public static func == (lhs: BarcodeResponseList, rhs: BarcodeResponseList) -> Bool {
        lhs.barcodes == rhs.barcodes
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(barcodes.hashValue)
        
    }
}

