//
// BarcodeImageParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Barcode image optional parameters */
public final class BarcodeImageParams: @unchecked Sendable, Codable, Hashable {
    public static let resolutionRule = NumericRule<Float>(minimum: 1, exclusiveMinimum: false, maximum: 100_000, exclusiveMaximum: false, multipleOf: nil)
    public var imageFormat: BarcodeImageFormat?
    public var textLocation: CodeLocation?
    /** Specify the displaying bars and content Color. Value: Color name from https://reference.aspose.com/drawing/net/system.drawing/color/ or ARGB value started with #. For example: AliceBlue or #FF000000 Default value: Black. */
    public var foregroundColor: String? = "Black"
    /** Background color of the barcode image. Value: Color name from https://reference.aspose.com/drawing/net/system.drawing/color/ or ARGB value started with #. For example: AliceBlue or #FF000000 Default value: White. */
    public var backgroundColor: String? = "White"
    public var units: GraphicsUnit?
    /** Resolution of the BarCode image. One value for both dimensions. Default value: 96 dpi. Decimal separator is dot. */
    public var resolution: Float?
    /** Height of the barcode image in given units. Default units: pixel. Decimal separator is dot. */
    public var imageHeight: Float?
    /** Width of the barcode image in given units. Default units: pixel. Decimal separator is dot. */
    public var imageWidth: Float?
    /** BarCode image rotation angle, measured in degree, e.g. RotationAngle = 0 or RotationAngle = 360 means no rotation. If RotationAngle NOT equal to 90, 180, 270 or 0, it may increase the difficulty for the scanner to read the image. Default value: 0. */
    public var rotationAngle: Int?

    public init(imageFormat: BarcodeImageFormat? = nil, textLocation: CodeLocation? = nil, foregroundColor: String? = "Black", backgroundColor: String? = "White", units: GraphicsUnit? = nil, resolution: Float? = nil, imageHeight: Float? = nil, imageWidth: Float? = nil, rotationAngle: Int? = nil) {
        self.imageFormat = imageFormat
        self.textLocation = textLocation
        self.foregroundColor = foregroundColor
        self.backgroundColor = backgroundColor
        self.units = units
        self.resolution = resolution
        self.imageHeight = imageHeight
        self.imageWidth = imageWidth
        self.rotationAngle = rotationAngle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageFormat
        case textLocation
        case foregroundColor
        case backgroundColor
        case units
        case resolution
        case imageHeight
        case imageWidth
        case rotationAngle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imageFormat, forKey: .imageFormat)
        try container.encodeIfPresent(textLocation, forKey: .textLocation)
        try container.encodeIfPresent(foregroundColor, forKey: .foregroundColor)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(resolution, forKey: .resolution)
        try container.encodeIfPresent(imageHeight, forKey: .imageHeight)
        try container.encodeIfPresent(imageWidth, forKey: .imageWidth)
        try container.encodeIfPresent(rotationAngle, forKey: .rotationAngle)
    }

    public static func == (lhs: BarcodeImageParams, rhs: BarcodeImageParams) -> Bool {
        lhs.imageFormat == rhs.imageFormat &&
            lhs.textLocation == rhs.textLocation &&
            lhs.foregroundColor == rhs.foregroundColor &&
            lhs.backgroundColor == rhs.backgroundColor &&
            lhs.units == rhs.units &&
            lhs.resolution == rhs.resolution &&
            lhs.imageHeight == rhs.imageHeight &&
            lhs.imageWidth == rhs.imageWidth &&
            lhs.rotationAngle == rhs.rotationAngle
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(imageFormat?.hashValue)
        hasher.combine(textLocation?.hashValue)
        hasher.combine(foregroundColor?.hashValue)
        hasher.combine(backgroundColor?.hashValue)
        hasher.combine(units?.hashValue)
        hasher.combine(resolution?.hashValue)
        hasher.combine(imageHeight?.hashValue)
        hasher.combine(imageWidth?.hashValue)
        hasher.combine(rotationAngle?.hashValue)
    }
}
