//
// BarcodeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represents information about barcode. */
public struct BarcodeResponse: Codable, JSONEncodable, Hashable {

    /** Barcode data. */
    public var barcodeValue: String?
    /** Type of the barcode. */
    public var type: String?
    /** Region with barcode. */
    public var region: [RegionPoint]?
    /** Checksum of barcode. */
    public var checksum: String?

    public init(barcodeValue: String? = nil, type: String? = nil, region: [RegionPoint]? = nil, checksum: String? = nil) {
        self.barcodeValue = barcodeValue
        self.type = type
        self.region = region
        self.checksum = checksum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case barcodeValue
        case type
        case region
        case checksum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(barcodeValue, forKey: .barcodeValue)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(checksum, forKey: .checksum)
    }
}

