//
// Code128Params.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional Code128 barcode generation parameters. */
public final class Code128Params: @unchecked Sendable, Codable, Hashable {
    /** Code128 barcode encode mode. Controls which Code 128 subset (A, B, C, or mix) is used. */
    public var code128EncodeMode: Code128EncodeMode?

    public init(code128EncodeMode: Code128EncodeMode? = nil) {
        self.code128EncodeMode = code128EncodeMode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code128EncodeMode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code128EncodeMode, forKey: .code128EncodeMode)
    }

    public static func == (lhs: Code128Params, rhs: Code128Params) -> Bool {
        lhs.code128EncodeMode == rhs.code128EncodeMode
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(code128EncodeMode?.hashValue)
    }
}
