//
// CodeLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CodeLocation: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case below = "Below"
    case above = "Above"
    case _none = "None"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
