//
// Code128EncodeMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Code128 barcode encode mode. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/code128encodemode/ */
public enum Code128EncodeMode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case auto = "Auto"
    case codeA = "CodeA"
    case codeB = "CodeB"
    case codeAB = "CodeAB"
    case codeC = "CodeC"
    case codeAC = "CodeAC"
    case codeBC = "CodeBC"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
