//
// ECIEncodings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ECI encoding identifiers. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/eciencodings/ */
public enum ECIEncodings: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _none = "NONE"
    case iso88591 = "ISO_8859_1"
    case iso88592 = "ISO_8859_2"
    case iso88593 = "ISO_8859_3"
    case iso88594 = "ISO_8859_4"
    case iso88595 = "ISO_8859_5"
    case iso88596 = "ISO_8859_6"
    case iso88597 = "ISO_8859_7"
    case iso88598 = "ISO_8859_8"
    case iso88599 = "ISO_8859_9"
    case iso885910 = "ISO_8859_10"
    case iso885911 = "ISO_8859_11"
    case iso885913 = "ISO_8859_13"
    case iso885914 = "ISO_8859_14"
    case iso885915 = "ISO_8859_15"
    case iso885916 = "ISO_8859_16"
    case shiftJis = "Shift_JIS"
    case win1250 = "Win1250"
    case win1251 = "Win1251"
    case win1252 = "Win1252"
    case win1256 = "Win1256"
    case utf16be = "UTF16BE"
    case utf8 = "UTF8"
    case usAscii = "US_ASCII"
    case big5 = "Big5"
    case gb2312 = "GB2312"
    case eucKr = "EUC_KR"
    case gbk = "GBK"
    case gb18030 = "GB18030"
    case utf16le = "UTF16LE"
    case utf32be = "UTF32BE"
    case utf32le = "UTF32LE"
    case invariant = "INVARIANT"
    case binary = "BINARY"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
