//
// EncodeDataType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Types of data that can be encoded into a barcode. */
public enum EncodeDataType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case stringData = "StringData"
    case base64Bytes = "Base64Bytes"
    case hexBytes = "HexBytes"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
