//
// EncodeData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Data to encode in barcode */
public final class EncodeData: @unchecked Sendable, Codable, Hashable {

    public static let dataRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var dataType: EncodeDataType?
    /** String represents data to encode */
    public var data: String

    public init(dataType: EncodeDataType? = nil, data: String) {
        self.dataType = dataType
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataType
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dataType, forKey: .dataType)
        try container.encode(data, forKey: .data)
    }

    public static func == (lhs: EncodeData, rhs: EncodeData) -> Bool {
        lhs.dataType == rhs.dataType &&
        lhs.data == rhs.data
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dataType?.hashValue)
        hasher.combine(data.hashValue)
        
    }
}

