//
// GenerateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Barcode generation parameters */
public final class GenerateParams: @unchecked Sendable, Codable, Hashable {

    public var barcodeType: EncodeBarcodeType
    public var encodeData: EncodeData
    public var barcodeImageParams: BarcodeImageParams?

    public init(barcodeType: EncodeBarcodeType, encodeData: EncodeData, barcodeImageParams: BarcodeImageParams? = nil) {
        self.barcodeType = barcodeType
        self.encodeData = encodeData
        self.barcodeImageParams = barcodeImageParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case barcodeType
        case encodeData
        case barcodeImageParams
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(barcodeType, forKey: .barcodeType)
        try container.encode(encodeData, forKey: .encodeData)
        try container.encodeIfPresent(barcodeImageParams, forKey: .barcodeImageParams)
    }

    public static func == (lhs: GenerateParams, rhs: GenerateParams) -> Bool {
        lhs.barcodeType == rhs.barcodeType &&
        lhs.encodeData == rhs.encodeData &&
        lhs.barcodeImageParams == rhs.barcodeImageParams
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(barcodeType.hashValue)
        hasher.combine(encodeData.hashValue)
        hasher.combine(barcodeImageParams?.hashValue)
        
    }
}

