//
// GraphicsUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Subset of Aspose.Drawing.GraphicsUnit. */
public enum GraphicsUnit: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case pixel = "Pixel"
    case point = "Point"
    case inch = "Inch"
    case millimeter = "Millimeter"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
