//
// GraphicsUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Subset of https://reference.aspose.com/drawing/net/system.drawing/graphicsunit/ */
public enum GraphicsUnit: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case pixel = "Pixel"
    case point = "Point"
    case inch = "Inch"
    case millimeter = "Millimeter"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
