//
// MacroCharacter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PDF417 macro character mode. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/macrocharacter/ */
public enum MacroCharacter: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _none = "None"
    case macro05 = "Macro05"
    case macro06 = "Macro06"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
