//
// MicroQRVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** MicroQR barcode version. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/microqrversion/ */
public enum MicroQRVersion: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case auto = "Auto"
    case m1 = "M1"
    case m2 = "M2"
    case m3 = "M3"
    case m4 = "M4"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
