//
// Pdf417ErrorLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PDF417 barcode error correction level. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/pdf417errorlevel/ */
public enum Pdf417ErrorLevel: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case level0 = "Level0"
    case level1 = "Level1"
    case level2 = "Level2"
    case level3 = "Level3"
    case level4 = "Level4"
    case level5 = "Level5"
    case level6 = "Level6"
    case level7 = "Level7"
    case level8 = "Level8"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
