//
// Pdf417Params.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional PDF417 barcode generation parameters. Applies to Pdf417, MacroPdf417, MicroPdf417, and GS1MicroPdf417 barcode types. */
public final class Pdf417Params: @unchecked Sendable, Codable, Hashable {
    public static let pdf417ColumnsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 30, exclusiveMaximum: false, multipleOf: nil)
    public static let pdf417RowsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 90, exclusiveMaximum: false, multipleOf: nil)
    public static let pdf417AspectRatioRule = NumericRule<Float>(minimum: 2, exclusiveMinimum: false, maximum: 10, exclusiveMaximum: false, multipleOf: nil)
    /** PDF417 barcode encode mode. */
    public var pdf417EncodeMode: Pdf417EncodeMode?
    /** PDF417 barcode error correction level. */
    public var pdf417ErrorLevel: Pdf417ErrorLevel?
    /** Whether to use truncated PDF417 format (removes right-side stop pattern). */
    public var pdf417Truncate: Bool?
    /** Number of columns in the PDF417 barcode. Values between 1 and 30. 0 for auto. */
    public var pdf417Columns: Int?
    /** Number of rows in the PDF417 barcode. Values between 3 and 90. 0 for automatic. */
    public var pdf417Rows: Int?
    /** PDF417 barcode aspect ratio (height/width of the barcode module). Values are defined by the standard: 2 to 5 for MicroPdf417; 3 to 5 for Pdf417 and MacroPdf417. */
    public var pdf417AspectRatio: Float?
    /** ECI encoding for PDF417 barcode data. */
    public var pdf417ECIEncoding: ECIEncodings?
    /** Whether the barcode is used for reader initialization (programming). */
    public var pdf417IsReaderInitialization: Bool?
    /** Macro character to prepend (structured append). */
    public var pdf417MacroCharacters: MacroCharacter?
    /** Whether to use linked mode (for MicroPdf417). */
    public var pdf417IsLinked: Bool?
    /** Whether to use Code128 emulation for MicroPdf417. */
    public var pdf417IsCode128Emulation: Bool?

    public init(pdf417EncodeMode: Pdf417EncodeMode? = nil, pdf417ErrorLevel: Pdf417ErrorLevel? = nil, pdf417Truncate: Bool? = nil, pdf417Columns: Int? = nil, pdf417Rows: Int? = nil, pdf417AspectRatio: Float? = nil, pdf417ECIEncoding: ECIEncodings? = nil, pdf417IsReaderInitialization: Bool? = nil, pdf417MacroCharacters: MacroCharacter? = nil, pdf417IsLinked: Bool? = nil, pdf417IsCode128Emulation: Bool? = nil) {
        self.pdf417EncodeMode = pdf417EncodeMode
        self.pdf417ErrorLevel = pdf417ErrorLevel
        self.pdf417Truncate = pdf417Truncate
        self.pdf417Columns = pdf417Columns
        self.pdf417Rows = pdf417Rows
        self.pdf417AspectRatio = pdf417AspectRatio
        self.pdf417ECIEncoding = pdf417ECIEncoding
        self.pdf417IsReaderInitialization = pdf417IsReaderInitialization
        self.pdf417MacroCharacters = pdf417MacroCharacters
        self.pdf417IsLinked = pdf417IsLinked
        self.pdf417IsCode128Emulation = pdf417IsCode128Emulation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pdf417EncodeMode
        case pdf417ErrorLevel
        case pdf417Truncate
        case pdf417Columns
        case pdf417Rows
        case pdf417AspectRatio
        case pdf417ECIEncoding
        case pdf417IsReaderInitialization
        case pdf417MacroCharacters
        case pdf417IsLinked
        case pdf417IsCode128Emulation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pdf417EncodeMode, forKey: .pdf417EncodeMode)
        try container.encodeIfPresent(pdf417ErrorLevel, forKey: .pdf417ErrorLevel)
        try container.encodeIfPresent(pdf417Truncate, forKey: .pdf417Truncate)
        try container.encodeIfPresent(pdf417Columns, forKey: .pdf417Columns)
        try container.encodeIfPresent(pdf417Rows, forKey: .pdf417Rows)
        try container.encodeIfPresent(pdf417AspectRatio, forKey: .pdf417AspectRatio)
        try container.encodeIfPresent(pdf417ECIEncoding, forKey: .pdf417ECIEncoding)
        try container.encodeIfPresent(pdf417IsReaderInitialization, forKey: .pdf417IsReaderInitialization)
        try container.encodeIfPresent(pdf417MacroCharacters, forKey: .pdf417MacroCharacters)
        try container.encodeIfPresent(pdf417IsLinked, forKey: .pdf417IsLinked)
        try container.encodeIfPresent(pdf417IsCode128Emulation, forKey: .pdf417IsCode128Emulation)
    }

    public static func == (lhs: Pdf417Params, rhs: Pdf417Params) -> Bool {
        lhs.pdf417EncodeMode == rhs.pdf417EncodeMode &&
            lhs.pdf417ErrorLevel == rhs.pdf417ErrorLevel &&
            lhs.pdf417Truncate == rhs.pdf417Truncate &&
            lhs.pdf417Columns == rhs.pdf417Columns &&
            lhs.pdf417Rows == rhs.pdf417Rows &&
            lhs.pdf417AspectRatio == rhs.pdf417AspectRatio &&
            lhs.pdf417ECIEncoding == rhs.pdf417ECIEncoding &&
            lhs.pdf417IsReaderInitialization == rhs.pdf417IsReaderInitialization &&
            lhs.pdf417MacroCharacters == rhs.pdf417MacroCharacters &&
            lhs.pdf417IsLinked == rhs.pdf417IsLinked &&
            lhs.pdf417IsCode128Emulation == rhs.pdf417IsCode128Emulation
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pdf417EncodeMode?.hashValue)
        hasher.combine(pdf417ErrorLevel?.hashValue)
        hasher.combine(pdf417Truncate?.hashValue)
        hasher.combine(pdf417Columns?.hashValue)
        hasher.combine(pdf417Rows?.hashValue)
        hasher.combine(pdf417AspectRatio?.hashValue)
        hasher.combine(pdf417ECIEncoding?.hashValue)
        hasher.combine(pdf417IsReaderInitialization?.hashValue)
        hasher.combine(pdf417MacroCharacters?.hashValue)
        hasher.combine(pdf417IsLinked?.hashValue)
        hasher.combine(pdf417IsCode128Emulation?.hashValue)
    }
}
