//
// Pdf417EncodeMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PDF417 barcode encode mode. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/pdf417encodemode/ */
public enum Pdf417EncodeMode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case auto = "Auto"
    case binary = "Binary"
    case eci = "ECI"
    case extended = "Extended"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
