//
// QREncodeMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** QR barcode encode mode. Subset of https://reference.aspose.com/barcode/net/aspose.barcode.generation/qrencodemode/ Obsolete members (Bytes, Utf8BOM, Utf16BEBOM, ECIEncoding, ExtendedCodetext) are omitted. */
public enum QREncodeMode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case auto = "Auto"
    case extended = "Extended"
    case binary = "Binary"
    case eci = "ECI"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
