//
// QRErrorLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** QR barcode error correction level. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/qrerrorlevel/ */
public enum QRErrorLevel: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case levelL = "LevelL"
    case levelM = "LevelM"
    case levelQ = "LevelQ"
    case levelH = "LevelH"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
