//
// QrParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional QR barcode generation parameters. Applies to QR, GS1QR, MicroQR, and RectMicroQR barcode types. */
public final class QrParams: @unchecked Sendable, Codable, Hashable {
    public static let qrAspectRatioRule = NumericRule<Float>(minimum: 0.001, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    /** QR barcode encode mode. */
    public var qrEncodeMode: QREncodeMode?
    /** QR barcode error correction level. */
    public var qrErrorLevel: QRErrorLevel?
    /** QR barcode version. Automatically selects the smallest version that fits the data. */
    public var qrVersion: QRVersion?
    /** ECI encoding for QR barcode data. */
    public var qrECIEncoding: ECIEncodings?
    /** QR barcode aspect ratio. Values: 0 to 1. */
    public var qrAspectRatio: Float?
    /** MicroQR barcode version. Used when BarcodeType is MicroQR. */
    public var microQRVersion: MicroQRVersion?
    /** RectMicroQR barcode version. Used when BarcodeType is RectMicroQR. */
    public var rectMicroQrVersion: RectMicroQRVersion?

    public init(qrEncodeMode: QREncodeMode? = nil, qrErrorLevel: QRErrorLevel? = nil, qrVersion: QRVersion? = nil, qrECIEncoding: ECIEncodings? = nil, qrAspectRatio: Float? = nil, microQRVersion: MicroQRVersion? = nil, rectMicroQrVersion: RectMicroQRVersion? = nil) {
        self.qrEncodeMode = qrEncodeMode
        self.qrErrorLevel = qrErrorLevel
        self.qrVersion = qrVersion
        self.qrECIEncoding = qrECIEncoding
        self.qrAspectRatio = qrAspectRatio
        self.microQRVersion = microQRVersion
        self.rectMicroQrVersion = rectMicroQrVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case qrEncodeMode
        case qrErrorLevel
        case qrVersion
        case qrECIEncoding
        case qrAspectRatio
        case microQRVersion
        case rectMicroQrVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(qrEncodeMode, forKey: .qrEncodeMode)
        try container.encodeIfPresent(qrErrorLevel, forKey: .qrErrorLevel)
        try container.encodeIfPresent(qrVersion, forKey: .qrVersion)
        try container.encodeIfPresent(qrECIEncoding, forKey: .qrECIEncoding)
        try container.encodeIfPresent(qrAspectRatio, forKey: .qrAspectRatio)
        try container.encodeIfPresent(microQRVersion, forKey: .microQRVersion)
        try container.encodeIfPresent(rectMicroQrVersion, forKey: .rectMicroQrVersion)
    }

    public static func == (lhs: QrParams, rhs: QrParams) -> Bool {
        lhs.qrEncodeMode == rhs.qrEncodeMode &&
            lhs.qrErrorLevel == rhs.qrErrorLevel &&
            lhs.qrVersion == rhs.qrVersion &&
            lhs.qrECIEncoding == rhs.qrECIEncoding &&
            lhs.qrAspectRatio == rhs.qrAspectRatio &&
            lhs.microQRVersion == rhs.microQRVersion &&
            lhs.rectMicroQrVersion == rhs.rectMicroQrVersion
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(qrEncodeMode?.hashValue)
        hasher.combine(qrErrorLevel?.hashValue)
        hasher.combine(qrVersion?.hashValue)
        hasher.combine(qrECIEncoding?.hashValue)
        hasher.combine(qrAspectRatio?.hashValue)
        hasher.combine(microQRVersion?.hashValue)
        hasher.combine(rectMicroQrVersion?.hashValue)
    }
}
