//
// QRVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** QR barcode version. Subset of https://reference.aspose.com/barcode/net/aspose.barcode.generation/qrversion/ MicroQR versions (VersionM1–VersionM4) are omitted; use Aspose.BarCode.Cloud.DTO.Enums.MicroQRVersion instead. */
public enum QRVersion: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case auto = "Auto"
    case version01 = "Version01"
    case version02 = "Version02"
    case version03 = "Version03"
    case version04 = "Version04"
    case version05 = "Version05"
    case version06 = "Version06"
    case version07 = "Version07"
    case version08 = "Version08"
    case version09 = "Version09"
    case version10 = "Version10"
    case version11 = "Version11"
    case version12 = "Version12"
    case version13 = "Version13"
    case version14 = "Version14"
    case version15 = "Version15"
    case version16 = "Version16"
    case version17 = "Version17"
    case version18 = "Version18"
    case version19 = "Version19"
    case version20 = "Version20"
    case version21 = "Version21"
    case version22 = "Version22"
    case version23 = "Version23"
    case version24 = "Version24"
    case version25 = "Version25"
    case version26 = "Version26"
    case version27 = "Version27"
    case version28 = "Version28"
    case version29 = "Version29"
    case version30 = "Version30"
    case version31 = "Version31"
    case version32 = "Version32"
    case version33 = "Version33"
    case version34 = "Version34"
    case version35 = "Version35"
    case version36 = "Version36"
    case version37 = "Version37"
    case version38 = "Version38"
    case version39 = "Version39"
    case version40 = "Version40"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
