//
// RecognitionImageKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Kind of image to recognize */
public enum RecognitionImageKind: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case photo = "Photo"
    case scannedDocument = "ScannedDocument"
    case clearImage = "ClearImage"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
