//
// RecognitionMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Recognition mode. */
public enum RecognitionMode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case fast = "Fast"
    case normal = "Normal"
    case excellent = "Excellent"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
