//
// RecognitionImageKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Kind of image to recognize */
public enum RecognitionImageKind: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case photo = "Photo"
    case scannedDocument = "ScannedDocument"
    case clearImage = "ClearImage"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
