//
// RecognizeBase64Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Barcode recognize request */
public struct RecognizeBase64Request: Codable, JSONEncodable, Hashable {

    static let fileBase64Rule = StringRule(minLength: 1, maxLength: 28730982, pattern: nil)
    /** Array of decode types to find on barcode */
    public var barcodeTypes: [DecodeBarcodeType]
    /** Barcode image bytes encoded as base-64. */
    public var fileBase64: String
    public var recognitionMode: RecognitionMode?
    public var recognitionImageKind: RecognitionImageKind?

    public init(barcodeTypes: [DecodeBarcodeType], fileBase64: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil) {
        self.barcodeTypes = barcodeTypes
        self.fileBase64 = fileBase64
        self.recognitionMode = recognitionMode
        self.recognitionImageKind = recognitionImageKind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case barcodeTypes
        case fileBase64
        case recognitionMode
        case recognitionImageKind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(barcodeTypes, forKey: .barcodeTypes)
        try container.encode(fileBase64, forKey: .fileBase64)
        try container.encodeIfPresent(recognitionMode, forKey: .recognitionMode)
        try container.encodeIfPresent(recognitionImageKind, forKey: .recognitionImageKind)
    }
}

