//
// RecognizeBase64Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Barcode recognition request. */
public final class RecognizeBase64Request: @unchecked Sendable, Codable, Hashable {
    public static let fileBase64Rule = StringRule(minLength: 1, maxLength: 28_730_982, pattern: nil)
    /** Array of barcode decode types to find. */
    public var barcodeTypes: [DecodeBarcodeType]
    /** Barcode image bytes encoded as base-64. */
    public var fileBase64: String
    /** Barcode recognition mode. */
    public var recognitionMode: RecognitionMode?
    /** Image kind for recognition. */
    public var recognitionImageKind: RecognitionImageKind?

    public init(barcodeTypes: [DecodeBarcodeType], fileBase64: String, recognitionMode: RecognitionMode? = nil, recognitionImageKind: RecognitionImageKind? = nil) {
        self.barcodeTypes = barcodeTypes
        self.fileBase64 = fileBase64
        self.recognitionMode = recognitionMode
        self.recognitionImageKind = recognitionImageKind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case barcodeTypes
        case fileBase64
        case recognitionMode
        case recognitionImageKind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(barcodeTypes, forKey: .barcodeTypes)
        try container.encode(fileBase64, forKey: .fileBase64)
        try container.encodeIfPresent(recognitionMode, forKey: .recognitionMode)
        try container.encodeIfPresent(recognitionImageKind, forKey: .recognitionImageKind)
    }

    public static func == (lhs: RecognizeBase64Request, rhs: RecognizeBase64Request) -> Bool {
        lhs.barcodeTypes == rhs.barcodeTypes &&
            lhs.fileBase64 == rhs.fileBase64 &&
            lhs.recognitionMode == rhs.recognitionMode &&
            lhs.recognitionImageKind == rhs.recognitionImageKind
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(barcodeTypes.hashValue)
        hasher.combine(fileBase64.hashValue)
        hasher.combine(recognitionMode?.hashValue)
        hasher.combine(recognitionImageKind?.hashValue)
    }
}
