//
// RectMicroQRVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** RectMicroQR barcode version. Mirrors https://reference.aspose.com/barcode/net/aspose.barcode.generation/rectmicroqrversion/ */
public enum RectMicroQRVersion: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case auto = "Auto"
    case r7x43 = "R7x43"
    case r7x59 = "R7x59"
    case r7x77 = "R7x77"
    case r7x99 = "R7x99"
    case r7x139 = "R7x139"
    case r9x43 = "R9x43"
    case r9x59 = "R9x59"
    case r9x77 = "R9x77"
    case r9x99 = "R9x99"
    case r9x139 = "R9x139"
    case r11x27 = "R11x27"
    case r11x43 = "R11x43"
    case r11x59 = "R11x59"
    case r11x77 = "R11x77"
    case r11x99 = "R11x99"
    case r11x139 = "R11x139"
    case r13x27 = "R13x27"
    case r13x43 = "R13x43"
    case r13x59 = "R13x59"
    case r13x77 = "R13x77"
    case r13x99 = "R13x99"
    case r13x139 = "R13x139"
    case r15x43 = "R15x43"
    case r15x59 = "R15x59"
    case r15x77 = "R15x77"
    case r15x99 = "R15x99"
    case r15x139 = "R15x139"
    case r17x43 = "R17x43"
    case r17x59 = "R17x59"
    case r17x77 = "R17x77"
    case r17x99 = "R17x99"
    case r17x139 = "R17x139"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
