//
// RegionPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Wrapper around Drawing.Point for proper specification. */
public final class RegionPoint: @unchecked Sendable, Codable, Hashable {
    /** X-coordinate */
    public var x: Int?
    /** Y-coordinate */
    public var y: Int?

    public init(x: Int? = nil, y: Int? = nil) {
        self.x = x
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case x
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(x, forKey: .x)
        try container.encodeIfPresent(y, forKey: .y)
    }

    public static func == (lhs: RegionPoint, rhs: RegionPoint) -> Bool {
        lhs.x == rhs.x &&
            lhs.y == rhs.y
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x?.hashValue)
        hasher.combine(y?.hashValue)
    }
}
