//
// ScanBase64Request.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Scan barcode request. */
public final class ScanBase64Request: Codable, JSONEncodable, Hashable {

    static let fileBase64Rule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Barcode image bytes encoded as base-64. */
    public var fileBase64: String

    public init(fileBase64: String) {
        self.fileBase64 = fileBase64
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileBase64
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fileBase64, forKey: .fileBase64)
    }

    public static func == (lhs: ScanBase64Request, rhs: ScanBase64Request) -> Bool {
        lhs.fileBase64 == rhs.fileBase64
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fileBase64.hashValue)
        
    }
}

