//
// CodableHelper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CodableHelper: @unchecked Sendable {
    // MARK: - Private state

    private struct State {
        var customDateFormatter: DateFormatter?
        var defaultDateFormatter: DateFormatter = OpenISO8601DateFormatter()

        var customJSONDecoder: JSONDecoder?
        var defaultJSONDecoder: JSONDecoder = .init()

        var customJSONEncoder: JSONEncoder?
        var defaultJSONEncoder: JSONEncoder = .init()

        init() {
            defaultJSONEncoder.outputFormatting = .prettyPrinted
            rebuildDefaultCoders()
        }

        mutating func rebuildDefaultCoders() {
            defaultJSONDecoder.dateDecodingStrategy = .formatted(customDateFormatter ?? defaultDateFormatter)
            defaultJSONEncoder.dateEncodingStrategy = .formatted(customDateFormatter ?? defaultDateFormatter)
        }
    }

    private let _state = OpenAPIMutex(State())

    // MARK: - Init

    public init() {}

    // MARK: - Public interface

    public var dateFormatter: DateFormatter {
        get { _state.withValue { $0.customDateFormatter ?? $0.defaultDateFormatter } }
        set {
            _state.withValue { state in
                state.customDateFormatter = newValue
                state.rebuildDefaultCoders()
            }
        }
    }

    public var jsonDecoder: JSONDecoder {
        get { _state.withValue { $0.customJSONDecoder ?? $0.defaultJSONDecoder } }
        set { _state.withValue { $0.customJSONDecoder = newValue } }
    }

    public var jsonEncoder: JSONEncoder {
        get { _state.withValue { $0.customJSONEncoder ?? $0.defaultJSONEncoder } }
        set { _state.withValue { $0.customJSONEncoder = newValue } }
    }

    open func decode<T: Decodable>(_ type: T.Type, from data: Data) -> Swift.Result<T, Error> {
        Swift.Result { try jsonDecoder.decode(type, from: data) }
    }

    open func encode(_ value: some Encodable) -> Swift.Result<Data, Error> {
        Swift.Result { try jsonEncoder.encode(value) }
    }
}
