// OpenAPIMutex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

final class OpenAPIMutex<Value>: @unchecked Sendable {
    private var _value: Value
    private let lock = NSRecursiveLock()

    init(_ value: Value) {
        _value = value
    }

    var value: Value {
        lock.withLock { _value }
    }

    @discardableResult
    func withValue<Result>(
        _ body: (inout Value) throws -> Result
    ) rethrows -> Result {
        try lock.withLock { try body(&_value) }
    }
}
