// SynchronizedDictionary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

final class SynchronizedDictionary<K: Hashable, V>: @unchecked Sendable {
    private let _state = OpenAPIMutex<[K: V]>([:])

    subscript(key: K) -> V? {
        get { _state.value[key] }
        set { _state.withValue { $0[key] = newValue } }
    }
}
